# MiniPrompt's config file
[behaviour]
colored_exit_status = true			# prettify the exit status of the previous command
dirtrim = 2			# trim the CWD to only show x number of dirs
enhanced_autocompletion = true			# completion maps, tilde expansion, mark directories, ...
enhanced_history_format = true			# better format for your shell history: [%Y-%m-%d %T]
dircolors = true			# color directories

[primary_prompt]
prefix = "\[\e]0;\w\a\]"			# prompt prefix
ps_content = "</yellow>\w</nc></spc>"			# the actual content of your prompt
normal_symbol = "➜"			# symbol to use after the previous command succeeded
error_symbol = "✗"			# symbol to use after the previous command failed
succeeded = "green"			# $normal_mark's color after a command executed successfully
failed = "red"			# $error_mark's color after the previous command executed successfully

[extensions]
ext_git = false			# enable git extension (shows current working branch)
ext_hostname = false			# enable hostname expansion (shows an @<machine> in the prompt)
ext_kubernetes = false			# enable kubernetes extension (shows kubernetes' current context)
git_color = "cyan"			# color of the git extension
hostname_color = "cyan"			# color of the hostname extension
kubernetes_color = "cyan"			# color of the kubernetes extennsion
git_struct = "</cyan> </unit>"
git_symbol = ""			# symbol to use for the git extension
hostname_symbol = ""			# symbol to use for the hostname extension
kube_symbol = ""			# symbol to use for the kubernetes extension
